version: "3.9"

services:
  mongo:
    image: mongo
    networks:
      - vortex
    ports:
      - "27017:27017"
    restart: always
    
  mongo-seed:
    depends_on:
      - mongo
    image: stefanwalther/mongo-seed
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    volumes:
      - ./mongo-seed:/data
    command: mongorestore --host mongo --port 27017 --drop --db test data/dump/test
    networks:
      - app-network

  station:
    depends_on:
      - mongo
    environment:
      - AUTH_KEY=1234asdf1234asdf1234asdf1234asdf
      - DEVICE_NAME=Docker Station
    image: antonioparolisi/weather-vortex-station
    networks:
      - vortex
    ports:
      - "15600:15600"

  server:
    depends_on:
      - mongo
    environment:
      - CLIENT_URL=http://localhost:8080
      - MONGODB_URI=mongodb://mongo/test
      - USEREMAIL=${USEREMAIL}
      - PWDMAIL=${PWDMAIL}
      - SECRET=${SECRET}
      - RESET_PASSWORD_KEY=${RESET_PASSWORD_KEY}
      - OPEN_WEATHER_MAP_API_KEY=${OPEN_WEATHER_MAP_API_KEY}
      - TROPOSPHERE_API_KEY=${TROPOSPHERE_API_KEY}
    image: antonioparolisi/weather-vortex-server
    networks:
      - vortex
    ports:
      - "12000:12000"

  client:
    depends_on:
      - server
    environment:
      - PUBLIC_PATH=/
      - VUE_APP_SERVER_URL=localhost:12000
    image: antonioparolisi/wv-client # antonioparolisi/weather-vortex-client
    networks:
      - vortex
    ports:
      - "8080:8080"

networks:
  vortex:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "vortex-net"
